apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fav
  name: fav
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fav
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fav
    spec:
      containers:
        - image: gcr.io/qa-ingress-ai-site/fast-artistic-videos-docker
          imagePullPolicy: Always
          name: fav
          ports:
            - containerPort: 8338
              protocol: TCP
          resources:
            limits:
              cpu: 3
              memory: 10Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 3
              memory: 10Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DATE
              value: 2018-12-06T23:51:16.695Z
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
